name = "chinapoll-worker"
main = "worker/index.ts"
compatibility_date = "2026-10-08"

[vars]

[[d1_databases]]
binding = "DB"
database_name = "chinapoll-local"
database_id = "local"
migrations_dir = "./migrations"
